/**
 * File: equalizer_constants.rs
 * 
 * http://www.ipodlinux.org/ITunesDB/#Equalizer_Presets_file
 */

 /// Container constants
pub const EQUALIZER_PRESET_CONTAINER_OBJECT_KEY: &str = "mqed";
pub const EQUALIZER_NUMBER_OF_PRESETS_OFFSET: usize = 16;
pub const EQUALIZER_NUMBER_OF_PRESETS_LEN: usize = 4;

pub const EQUALIZER_PRESET_CHILDSIZE_OFFSET : usize = 20;
pub const EQUALIZER_PRESET_CHILDSIZE_LEN : usize = 4;
pub const EQUALIZER_PRESET_CHILDSIZE_VALUE : usize = 588;


pub const EQUALIZER_PRESET_PRESET_OBJECT_KEY: &str = "pqed";
pub const EQUALIZER_PRESET_PRESET_NAME_LENGTH_OFFSET : usize = 4;
pub const EQUALIZER_PRESET_FIELD_MAX_LENGTH : usize = 510;

pub const EQUALIZER_PRESET_NAME_OFFSET : usize = 6; // 4 + 2

pub const EQUALIZER_PREAMP_OFFSET : usize = 516; // 4 + 2 + 510
pub const EQUALIZER_PREAMP_LEN : usize = 4;

pub const EQUALIZER_NUM_OF_ITUNES_BANDS_OFFSET : usize = EQUALIZER_PREAMP_OFFSET + EQUALIZER_PREAMP_LEN;
pub const EQUALIZER_NUM_OF_ITUNES_BANDS_EXPECTED_VALUE : usize = 10;

pub const EQUALIZER_ITUNES_BAND_VALUES_OFFSET : usize = EQUALIZER_NUM_OF_ITUNES_BANDS_OFFSET + 4;
pub const EQUALIZER_ITUNES_BAND_VALUES_LEN : usize = 40;

pub const MAX_EQUALIZER_BAND_VALUE : i32 = 1200;
pub const MIN_EQUALIZER_BAND_VALUE : i32 = -1200;

pub const EQUALIZER_NUM_OF_DSP_BANDS_OFFSET : usize = EQUALIZER_ITUNES_BAND_VALUES_OFFSET + EQUALIZER_ITUNES_BAND_VALUES_LEN;
pub const EQUALIZER_NUM_OF_DSP_BANDS_EXPECTED_VALUE : usize = 5;

pub const EQUALIZER_DSP_BAND_VALUES_OFFSET : usize = EQUALIZER_NUM_OF_DSP_BANDS_OFFSET + 4;
pub const EQUALIZER_DSP_BAND_VALUES_LEN : usize = 20;