[package]
name = "ipod_tone_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# For sound playback
rodio = "0.17.3"

# Testing
hound = "3.5.1"